CREATE TABLE IF NOT EXISTS Genres (
	id SERIAL PRIMARY KEY,
	name VARCHAR(64) UNIQUE NOT NULL	
);

CREATE TABLE IF NOT EXISTS Artists (
	id SERIAL PRIMARY KEY,
	name VARCHAR(96) NOT NULL	
);

CREATE TABLE IF NOT EXISTS Albums (
	id SERIAL PRIMARY KEY,
	name VARCHAR(96) NOT NULL,
	year SMALLINT CHECK (year > 0) NOT NULL	
);

CREATE TABLE IF NOT EXISTS Tracks (
	id SERIAL PRIMARY KEY,
	album_id INTEGER NOT NULL REFERENCES Albums (id),
	name VARCHAR(96) NOT NULL,
	duratation NUMERIC(4,2) CHECK (duratation > 0) NOT NULL	
);

CREATE TABLE IF NOT EXISTS Collections (
	id SERIAL PRIMARY KEY,
	track_id INTEGER NOT NULL REFERENCES Tracks (id),
	name VARCHAR(96) NOT NULL,
	year SMALLINT CHECK (year > 0) NOT NULL	
);

CREATE TABLE IF NOT EXISTS Genre_Artist (
	id SERIAL PRIMARY KEY,
	genre_id INTEGER NOT NULL REFERENCES Genres (id),
	artist_id INTEGER NOT NULL REFERENCES Artists (id)
);

CREATE TABLE IF NOT EXISTS Artist_Album (
	id SERIAL PRIMARY KEY,
	artist_id INTEGER NOT NULL REFERENCES Artists (id),
	album_id INTEGER NOT NULL REFERENCES Albums (id)
);

CREATE TABLE IF NOT EXISTS Album_Track (
	id SERIAL PRIMARY KEY,
	album_id INTEGER NOT NULL REFERENCES Albums (id),
	track_id INTEGER NOT NULL REFERENCES Tracks (id)
);