CREATE TABLE IF NOT EXISTS Emails (
	id SERIAL PRIMARY KEY,
	email VARCHAR(64) NOT NULL UNIQUE CHECK(Email !='')	
);

CREATE TABLE IF NOT EXISTS Clients (
	id SERIAL PRIMARY KEY,
	email_id INTEGER NOT NULL REFERENCES Emails (id) ON DELETE CASCADE,
	name VARCHAR(32) NOT NULL,
	surname VARCHAR(96) NOT NULL	
);

CREATE TABLE IF NOT EXISTS Phones (
	id SERIAL PRIMARY KEY,
	client_id INTEGER NOT NULL REFERENCES Clients (id) ON DELETE CASCADE,
	phone_number VARCHAR(18) NOT NULL	
);