CREATE TABLE IF NOT EXISTS Users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(64) NOT NULL UNIQUE CHECK(name !='')
);

CREATE TABLE IF NOT EXISTS Words (
	id SERIAL PRIMARY KEY,
	ru_word VARCHAR(64) NOT NULL UNIQUE CHECK(ru_word !=''),
	en1_word VARCHAR(64) NOT NULL CHECK(en1_word !=''),
	en2_word VARCHAR(64) CHECK(en2_word !='')
);

CREATE TABLE IF NOT EXISTS Users_Words (
	id SERIAL PRIMARY KEY,
	id_user INTEGER NOT NULL REFERENCES Users (id) ON DELETE CASCADE,
	id_word INTEGER NOT NULL REFERENCES Words (id) ON DELETE CASCADE
);